### ISSUE TITLE
Denied permission on Linux

### ISSUE THREAD

**Issue by mikolasan** [mikolasan/oledbutton#1]
```
Traceback (most recent call last):
  File "/home/mikolasan/.local/lib/python3.7/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    btn.connect()
  File "/home/mikolasan/homework/oledbutton/oledbutton.py", line 33, in connect
    self.serial = serial.Serial(port, baudrate=115200, timeout=1, write_timeout=1, inter_byte_timeout=0.1)
  File "/home/mikolasan/.local/lib/python3.7/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/mikolasan/.local/lib/python3.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
```

**Comment by mikolasan** [comment]
```
$ ls -l /dev/ttyUSB0
crw-rw---- 1 root uucp 188, 0 May 26 13:30 /dev/ttyUSB0
$ sudo gpasswd -a mikolasan uucp
```
